// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF-T03DapOlSyCb5KptQxFmQZMWgqi248',
    appId: '1:536567239473:web:4e12133a2ad1f5594f1610',
    messagingSenderId: '536567239473',
    projectId: 'telehealth-consultation-app',
    authDomain: 'telehealth-consultation-app.firebaseapp.com',
    storageBucket: 'telehealth-consultation-app.firebasestorage.app',
    measurementId: 'G-85XYSSH5YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQXHAjMKgwUQPbD5-jai-f3vfZfn3pCVo',
    appId: '1:536567239473:android:cda865eef892eab34f1610',
    messagingSenderId: '536567239473',
    projectId: 'telehealth-consultation-app',
    storageBucket: 'telehealth-consultation-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAQjMehsQGwiMA5s1D2LnATml9OvPIeew',
    appId: '1:536567239473:ios:2a1c6199852227ea4f1610',
    messagingSenderId: '536567239473',
    projectId: 'telehealth-consultation-app',
    storageBucket: 'telehealth-consultation-app.firebasestorage.app',
    iosBundleId: 'com.example.telehealthConsultationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAQjMehsQGwiMA5s1D2LnATml9OvPIeew',
    appId: '1:536567239473:ios:2a1c6199852227ea4f1610',
    messagingSenderId: '536567239473',
    projectId: 'telehealth-consultation-app',
    storageBucket: 'telehealth-consultation-app.firebasestorage.app',
    iosBundleId: 'com.example.telehealthConsultationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF-T03DapOlSyCb5KptQxFmQZMWgqi248',
    appId: '1:536567239473:web:15be2579604ee97e4f1610',
    messagingSenderId: '536567239473',
    projectId: 'telehealth-consultation-app',
    authDomain: 'telehealth-consultation-app.firebaseapp.com',
    storageBucket: 'telehealth-consultation-app.firebasestorage.app',
    measurementId: 'G-Q5Z8FL4ZFZ',
  );
}
